
package net.mcreator.paperdrawermod.item;

import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.Level;
import net.minecraft.world.item.crafting.Ingredient;
import net.minecraft.world.item.TooltipFlag;
import net.minecraft.world.item.Tier;
import net.minecraft.world.item.PickaxeItem;
import net.minecraft.world.item.Items;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.network.chat.TextComponent;
import net.minecraft.network.chat.Component;

import net.mcreator.paperdrawermod.init.PaperdrawermodModItems;
import net.mcreator.paperdrawermod.init.PaperdrawermodModBlocks;

import java.util.List;

public class O5GritItem extends PickaxeItem {
	public O5GritItem() {
		super(new Tier() {
			public int getUses() {
				return 100003;
			}

			public float getSpeed() {
				return 4f;
			}

			public float getAttackDamageBonus() {
				return 9998f;
			}

			public int getLevel() {
				return 1;
			}

			public int getEnchantmentValue() {
				return 99999;
			}

			public Ingredient getRepairIngredient() {
				return Ingredient.of(new ItemStack(PaperdrawermodModItems.PAPERSPAWNER.get()),
						new ItemStack(PaperdrawermodModItems.FACELESSPAPERSPAWNER.get()), new ItemStack(PaperdrawermodModBlocks.AUTO.get()),
						new ItemStack(PaperdrawermodModBlocks.PAPER_BLOCK.get()), new ItemStack(PaperdrawermodModItems.PAPER_DIMENSION.get()),
						new ItemStack(Blocks.AIR), new ItemStack(Blocks.VOID_AIR), new ItemStack(Blocks.CAVE_AIR), new ItemStack(Blocks.STONE),
						new ItemStack(Blocks.STONE_STAIRS), new ItemStack(Blocks.STONE_SLAB), new ItemStack(Blocks.GRANITE),
						new ItemStack(Blocks.POLISHED_GRANITE), new ItemStack(Blocks.GRANITE_STAIRS), new ItemStack(Blocks.POLISHED_GRANITE_STAIRS),
						new ItemStack(Blocks.GRANITE_SLAB), new ItemStack(Blocks.POLISHED_GRANITE_SLAB), new ItemStack(Blocks.GRANITE_WALL),
						new ItemStack(Blocks.DIORITE), new ItemStack(Blocks.DIORITE_STAIRS), new ItemStack(Blocks.DIORITE_SLAB),
						new ItemStack(Blocks.DIORITE_WALL), new ItemStack(Blocks.POLISHED_DIORITE), new ItemStack(Blocks.POLISHED_DIORITE_SLAB),
						new ItemStack(Blocks.POLISHED_DIORITE_STAIRS), new ItemStack(Blocks.ANDESITE), new ItemStack(Blocks.ANDESITE_STAIRS),
						new ItemStack(Blocks.ANDESITE_SLAB), new ItemStack(Blocks.ANDESITE_WALL), new ItemStack(Blocks.POLISHED_ANDESITE),
						new ItemStack(Blocks.POLISHED_ANDESITE_STAIRS), new ItemStack(Blocks.POLISHED_ANDESITE_SLAB),
						new ItemStack(Blocks.SMOOTH_STONE), new ItemStack(Blocks.DEEPSLATE), new ItemStack(Blocks.COBBLED_DEEPSLATE),
						new ItemStack(Blocks.COBBLED_DEEPSLATE_STAIRS), new ItemStack(Blocks.COBBLED_DEEPSLATE_SLAB),
						new ItemStack(Blocks.COBBLED_DEEPSLATE_WALL), new ItemStack(Blocks.POLISHED_DEEPSLATE),
						new ItemStack(Blocks.POLISHED_DEEPSLATE_STAIRS), new ItemStack(Blocks.POLISHED_DEEPSLATE_SLAB),
						new ItemStack(Blocks.POLISHED_DEEPSLATE_WALL), new ItemStack(Blocks.DEEPSLATE_TILES),
						new ItemStack(Blocks.DEEPSLATE_TILE_STAIRS), new ItemStack(Blocks.DEEPSLATE_TILE_SLAB),
						new ItemStack(Blocks.DEEPSLATE_TILE_WALL), new ItemStack(Blocks.DEEPSLATE_BRICKS),
						new ItemStack(Blocks.DEEPSLATE_BRICK_STAIRS), new ItemStack(Blocks.DEEPSLATE_BRICK_SLAB),
						new ItemStack(Blocks.DEEPSLATE_BRICK_WALL), new ItemStack(Blocks.CHISELED_DEEPSLATE),
						new ItemStack(Blocks.CRACKED_DEEPSLATE_BRICKS), new ItemStack(Blocks.CRACKED_DEEPSLATE_TILES), new ItemStack(Blocks.TUFF),
						new ItemStack(Blocks.CALCITE), new ItemStack(Blocks.DRIPSTONE_BLOCK), new ItemStack(Blocks.POINTED_DRIPSTONE),
						new ItemStack(Blocks.GRASS_BLOCK), new ItemStack(Blocks.DIRT_PATH), new ItemStack(Blocks.MYCELIUM),
						new ItemStack(Blocks.DIRT), new ItemStack(Blocks.COARSE_DIRT), new ItemStack(Blocks.PODZOL),
						new ItemStack(Blocks.ROOTED_DIRT), new ItemStack(Blocks.COBBLESTONE), new ItemStack(Blocks.MOSSY_COBBLESTONE),
						new ItemStack(Blocks.MOSSY_COBBLESTONE_STAIRS), new ItemStack(Blocks.MOSSY_COBBLESTONE_SLAB),
						new ItemStack(Blocks.MOSS_BLOCK), new ItemStack(Blocks.MOSS_CARPET), new ItemStack(Blocks.OAK_PLANKS),
						new ItemStack(Blocks.SPRUCE_PLANKS), new ItemStack(Blocks.BIRCH_PLANKS), new ItemStack(Blocks.JUNGLE_PLANKS),
						new ItemStack(Blocks.ACACIA_PLANKS), new ItemStack(Blocks.DARK_OAK_PLANKS), new ItemStack(Blocks.CRIMSON_PLANKS),
						new ItemStack(Blocks.WARPED_PLANKS), new ItemStack(Blocks.OAK_SAPLING), new ItemStack(Blocks.SPRUCE_SAPLING),
						new ItemStack(Blocks.BIRCH_SAPLING), new ItemStack(Blocks.JUNGLE_SAPLING), new ItemStack(Blocks.ACACIA_SAPLING),
						new ItemStack(Blocks.DARK_OAK_SAPLING), new ItemStack(Blocks.SUGAR_CANE), new ItemStack(Blocks.BEDROCK),
						new ItemStack(Blocks.SAND), new ItemStack(Blocks.RED_SAND), new ItemStack(Blocks.GRAVEL), new ItemStack(Blocks.WATER),
						new ItemStack(Blocks.WATER), new ItemStack(Blocks.BUBBLE_COLUMN), new ItemStack(Blocks.LAVA), new ItemStack(Blocks.LAVA),
						new ItemStack(Blocks.MAGMA_BLOCK), new ItemStack(Blocks.OBSIDIAN), new ItemStack(Blocks.CRYING_OBSIDIAN),
						new ItemStack(Blocks.BLACKSTONE), new ItemStack(Blocks.BLACKSTONE_STAIRS), new ItemStack(Blocks.BLACKSTONE_WALL),
						new ItemStack(Blocks.BLACKSTONE_SLAB), new ItemStack(Blocks.POLISHED_BLACKSTONE),
						new ItemStack(Blocks.POLISHED_BLACKSTONE_BRICKS), new ItemStack(Blocks.CRACKED_POLISHED_BLACKSTONE_BRICKS),
						new ItemStack(Blocks.CHISELED_POLISHED_BLACKSTONE), new ItemStack(Blocks.POLISHED_BLACKSTONE_BRICK_SLAB),
						new ItemStack(Blocks.POLISHED_BLACKSTONE_BRICK_STAIRS), new ItemStack(Blocks.POLISHED_BLACKSTONE_BRICK_WALL),
						new ItemStack(Blocks.POLISHED_BLACKSTONE_STAIRS), new ItemStack(Blocks.POLISHED_BLACKSTONE_SLAB),
						new ItemStack(Blocks.POLISHED_BLACKSTONE_WALL), new ItemStack(Blocks.COAL_ORE), new ItemStack(Blocks.IRON_ORE),
						new ItemStack(Blocks.REDSTONE_ORE), new ItemStack(Blocks.REDSTONE_ORE), new ItemStack(Blocks.GOLD_ORE),
						new ItemStack(Blocks.LAPIS_ORE), new ItemStack(Blocks.DIAMOND_ORE), new ItemStack(Blocks.EMERALD_ORE),
						new ItemStack(Blocks.COPPER_ORE), new ItemStack(Blocks.DEEPSLATE_COAL_ORE), new ItemStack(Blocks.DEEPSLATE_IRON_ORE),
						new ItemStack(Blocks.DEEPSLATE_REDSTONE_ORE), new ItemStack(Blocks.DEEPSLATE_GOLD_ORE),
						new ItemStack(Blocks.DEEPSLATE_LAPIS_ORE), new ItemStack(Blocks.DEEPSLATE_DIAMOND_ORE),
						new ItemStack(Blocks.DEEPSLATE_EMERALD_ORE), new ItemStack(Blocks.DEEPSLATE_COPPER_ORE),
						new ItemStack(Blocks.NETHER_QUARTZ_ORE), new ItemStack(Blocks.NETHER_GOLD_ORE), new ItemStack(Blocks.GILDED_BLACKSTONE),
						new ItemStack(Blocks.RAW_IRON_BLOCK), new ItemStack(Blocks.RAW_GOLD_BLOCK), new ItemStack(Blocks.RAW_COPPER_BLOCK),
						new ItemStack(Blocks.COAL_BLOCK), new ItemStack(Blocks.IRON_BLOCK), new ItemStack(Blocks.COPPER_BLOCK),
						new ItemStack(Blocks.EXPOSED_COPPER), new ItemStack(Blocks.WEATHERED_COPPER), new ItemStack(Blocks.OXIDIZED_COPPER),
						new ItemStack(Blocks.CUT_COPPER), new ItemStack(Blocks.EXPOSED_CUT_COPPER), new ItemStack(Blocks.WEATHERED_CUT_COPPER),
						new ItemStack(Blocks.OXIDIZED_CUT_COPPER), new ItemStack(Blocks.CUT_COPPER_STAIRS),
						new ItemStack(Blocks.EXPOSED_CUT_COPPER_STAIRS), new ItemStack(Blocks.WEATHERED_CUT_COPPER_STAIRS),
						new ItemStack(Blocks.OXIDIZED_CUT_COPPER_STAIRS), new ItemStack(Blocks.CUT_COPPER_SLAB),
						new ItemStack(Blocks.EXPOSED_CUT_COPPER_SLAB), new ItemStack(Blocks.WEATHERED_CUT_COPPER_SLAB),
						new ItemStack(Blocks.OXIDIZED_CUT_COPPER_SLAB), new ItemStack(Blocks.WAXED_COPPER_BLOCK),
						new ItemStack(Blocks.WAXED_EXPOSED_COPPER), new ItemStack(Blocks.WAXED_WEATHERED_COPPER),
						new ItemStack(Blocks.WAXED_OXIDIZED_COPPER), new ItemStack(Blocks.WAXED_CUT_COPPER),
						new ItemStack(Blocks.WAXED_EXPOSED_CUT_COPPER), new ItemStack(Blocks.WAXED_WEATHERED_CUT_COPPER),
						new ItemStack(Blocks.WAXED_OXIDIZED_CUT_COPPER), new ItemStack(Blocks.WAXED_CUT_COPPER_STAIRS),
						new ItemStack(Blocks.WAXED_EXPOSED_CUT_COPPER_STAIRS), new ItemStack(Blocks.WAXED_WEATHERED_CUT_COPPER_STAIRS),
						new ItemStack(Blocks.WAXED_OXIDIZED_CUT_COPPER_STAIRS), new ItemStack(Blocks.WAXED_CUT_COPPER_SLAB),
						new ItemStack(Blocks.WAXED_EXPOSED_CUT_COPPER_SLAB), new ItemStack(Blocks.WAXED_WEATHERED_CUT_COPPER_SLAB),
						new ItemStack(Blocks.WAXED_OXIDIZED_CUT_COPPER_SLAB), new ItemStack(Blocks.REDSTONE_BLOCK), new ItemStack(Blocks.GOLD_BLOCK),
						new ItemStack(Blocks.LAPIS_BLOCK), new ItemStack(Blocks.DIAMOND_BLOCK), new ItemStack(Blocks.EMERALD_BLOCK),
						new ItemStack(Blocks.NETHERITE_BLOCK), new ItemStack(Blocks.SMOOTH_QUARTZ), new ItemStack(Blocks.CHISELED_QUARTZ_BLOCK),
						new ItemStack(Blocks.QUARTZ_PILLAR), new ItemStack(Blocks.QUARTZ_BLOCK), new ItemStack(Blocks.QUARTZ_BRICKS),
						new ItemStack(Blocks.SMOOTH_QUARTZ_STAIRS), new ItemStack(Blocks.SMOOTH_QUARTZ_SLAB), new ItemStack(Blocks.SLIME_BLOCK),
						new ItemStack(Blocks.ANCIENT_DEBRIS), new ItemStack(Blocks.AMETHYST_BLOCK), new ItemStack(Blocks.BUDDING_AMETHYST),
						new ItemStack(Blocks.AMETHYST_CLUSTER), new ItemStack(Blocks.LARGE_AMETHYST_BUD), new ItemStack(Blocks.MEDIUM_AMETHYST_BUD),
						new ItemStack(Blocks.SMALL_AMETHYST_BUD), new ItemStack(Blocks.OAK_LOG), new ItemStack(Blocks.OAK_LOG),
						new ItemStack(Blocks.SPRUCE_LOG), new ItemStack(Blocks.BIRCH_LOG), new ItemStack(Blocks.JUNGLE_LOG),
						new ItemStack(Blocks.ACACIA_LOG), new ItemStack(Blocks.ACACIA_LOG), new ItemStack(Blocks.DARK_OAK_LOG),
						new ItemStack(Blocks.WARPED_STEM), new ItemStack(Blocks.CRIMSON_STEM), new ItemStack(Blocks.STRIPPED_OAK_LOG),
						new ItemStack(Blocks.STRIPPED_SPRUCE_LOG), new ItemStack(Blocks.STRIPPED_BIRCH_LOG),
						new ItemStack(Blocks.STRIPPED_JUNGLE_LOG), new ItemStack(Blocks.STRIPPED_ACACIA_LOG),
						new ItemStack(Blocks.STRIPPED_DARK_OAK_LOG), new ItemStack(Blocks.STRIPPED_WARPED_STEM),
						new ItemStack(Blocks.STRIPPED_CRIMSON_STEM), new ItemStack(Blocks.OAK_WOOD), new ItemStack(Blocks.SPRUCE_WOOD),
						new ItemStack(Blocks.BIRCH_WOOD), new ItemStack(Blocks.JUNGLE_WOOD), new ItemStack(Blocks.ACACIA_WOOD),
						new ItemStack(Blocks.DARK_OAK_WOOD), new ItemStack(Blocks.WARPED_HYPHAE), new ItemStack(Blocks.CRIMSON_HYPHAE),
						new ItemStack(Blocks.STRIPPED_OAK_WOOD), new ItemStack(Blocks.STRIPPED_SPRUCE_WOOD),
						new ItemStack(Blocks.STRIPPED_BIRCH_WOOD), new ItemStack(Blocks.STRIPPED_JUNGLE_WOOD),
						new ItemStack(Blocks.STRIPPED_ACACIA_WOOD), new ItemStack(Blocks.STRIPPED_DARK_OAK_WOOD),
						new ItemStack(Blocks.STRIPPED_WARPED_HYPHAE), new ItemStack(Blocks.STRIPPED_CRIMSON_HYPHAE), new ItemStack(Blocks.OAK_LEAVES),
						new ItemStack(Blocks.OAK_LEAVES), new ItemStack(Blocks.SPRUCE_LEAVES), new ItemStack(Blocks.BIRCH_LEAVES),
						new ItemStack(Blocks.JUNGLE_LEAVES), new ItemStack(Blocks.ACACIA_LEAVES), new ItemStack(Blocks.ACACIA_LEAVES),
						new ItemStack(Blocks.DARK_OAK_LEAVES), new ItemStack(Blocks.AZALEA_LEAVES), new ItemStack(Blocks.FLOWERING_AZALEA_LEAVES),
						new ItemStack(Blocks.SPONGE), new ItemStack(Blocks.WET_SPONGE), new ItemStack(Blocks.SANDSTONE),
						new ItemStack(Blocks.CHISELED_SANDSTONE), new ItemStack(Blocks.CUT_SANDSTONE), new ItemStack(Blocks.SANDSTONE_STAIRS),
						new ItemStack(Blocks.SMOOTH_SANDSTONE), new ItemStack(Blocks.SMOOTH_SANDSTONE_STAIRS),
						new ItemStack(Blocks.SMOOTH_SANDSTONE_SLAB), new ItemStack(Blocks.CUT_SANDSTONE_SLAB), new ItemStack(Blocks.SANDSTONE_WALL),
						new ItemStack(Blocks.RED_SANDSTONE), new ItemStack(Blocks.CHISELED_RED_SANDSTONE), new ItemStack(Blocks.CUT_RED_SANDSTONE),
						new ItemStack(Blocks.RED_SANDSTONE_STAIRS), new ItemStack(Blocks.SMOOTH_RED_SANDSTONE),
						new ItemStack(Blocks.SMOOTH_RED_SANDSTONE_STAIRS), new ItemStack(Blocks.SMOOTH_RED_SANDSTONE_SLAB),
						new ItemStack(Blocks.CUT_RED_SANDSTONE_SLAB), new ItemStack(Blocks.RED_SANDSTONE_WALL), new ItemStack(Blocks.NOTE_BLOCK),
						new ItemStack(Blocks.RAIL), new ItemStack(Blocks.POWERED_RAIL), new ItemStack(Blocks.DETECTOR_RAIL),
						new ItemStack(Blocks.ACTIVATOR_RAIL), new ItemStack(Blocks.WHITE_BED), new ItemStack(Blocks.ORANGE_BED),
						new ItemStack(Blocks.MAGENTA_BED), new ItemStack(Blocks.LIGHT_BLUE_BED), new ItemStack(Blocks.YELLOW_BED),
						new ItemStack(Blocks.LIME_BED), new ItemStack(Blocks.PINK_BED), new ItemStack(Blocks.GRAY_BED),
						new ItemStack(Blocks.LIGHT_GRAY_BED), new ItemStack(Blocks.CYAN_BED), new ItemStack(Blocks.PURPLE_BED),
						new ItemStack(Blocks.BLUE_BED), new ItemStack(Blocks.BROWN_BED), new ItemStack(Blocks.GREEN_BED),
						new ItemStack(Blocks.RED_BED), new ItemStack(Blocks.BLACK_BED), new ItemStack(Blocks.COBWEB), new ItemStack(Blocks.DEAD_BUSH),
						new ItemStack(Blocks.GRASS), new ItemStack(Blocks.DEAD_BUSH), new ItemStack(Blocks.GRASS), new ItemStack(Blocks.FERN),
						new ItemStack(Blocks.PISTON), new ItemStack(Blocks.STICKY_PISTON), new ItemStack(Blocks.PISTON_HEAD),
						new ItemStack(Blocks.MOVING_PISTON), new ItemStack(Blocks.DANDELION), new ItemStack(Blocks.POPPY),
						new ItemStack(Blocks.BLUE_ORCHID), new ItemStack(Blocks.ALLIUM), new ItemStack(Blocks.AZURE_BLUET),
						new ItemStack(Blocks.RED_TULIP), new ItemStack(Blocks.ORANGE_TULIP), new ItemStack(Blocks.WHITE_TULIP),
						new ItemStack(Blocks.PINK_TULIP), new ItemStack(Blocks.OXEYE_DAISY), new ItemStack(Blocks.CORNFLOWER),
						new ItemStack(Blocks.LILY_OF_THE_VALLEY), new ItemStack(Blocks.WITHER_ROSE), new ItemStack(Blocks.SUNFLOWER),
						new ItemStack(Blocks.LILAC), new ItemStack(Blocks.TALL_GRASS), new ItemStack(Blocks.LARGE_FERN),
						new ItemStack(Blocks.ROSE_BUSH), new ItemStack(Blocks.PEONY), new ItemStack(Blocks.BROWN_MUSHROOM),
						new ItemStack(Blocks.RED_MUSHROOM), new ItemStack(Blocks.WARPED_FUNGUS), new ItemStack(Blocks.CRIMSON_FUNGUS),
						new ItemStack(Blocks.BROWN_MUSHROOM_BLOCK), new ItemStack(Blocks.RED_MUSHROOM_BLOCK), new ItemStack(Blocks.WARPED_WART_BLOCK),
						new ItemStack(Blocks.MUSHROOM_STEM), new ItemStack(Blocks.BRICKS), new ItemStack(Blocks.BRICK_WALL),
						new ItemStack(Blocks.TNT), new ItemStack(Blocks.BOOKSHELF), new ItemStack(Blocks.TORCH), new ItemStack(Blocks.WALL_TORCH),
						new ItemStack(Blocks.SOUL_TORCH), new ItemStack(Blocks.SOUL_WALL_TORCH), new ItemStack(Blocks.FIRE),
						new ItemStack(Blocks.SOUL_FIRE), new ItemStack(Blocks.LANTERN), new ItemStack(Blocks.SOUL_LANTERN),
						new ItemStack(Blocks.CHAIN), new ItemStack(Blocks.CAMPFIRE), new ItemStack(Blocks.SOUL_CAMPFIRE),
						new ItemStack(Blocks.CANDLE), new ItemStack(Blocks.WHITE_CANDLE), new ItemStack(Blocks.ORANGE_CANDLE),
						new ItemStack(Blocks.MAGENTA_CANDLE), new ItemStack(Blocks.LIGHT_BLUE_CANDLE), new ItemStack(Blocks.YELLOW_CANDLE),
						new ItemStack(Blocks.LIME_CANDLE), new ItemStack(Blocks.PINK_CANDLE), new ItemStack(Blocks.GRAY_CANDLE),
						new ItemStack(Blocks.LIGHT_GRAY_CANDLE), new ItemStack(Blocks.CYAN_CANDLE), new ItemStack(Blocks.PURPLE_CANDLE),
						new ItemStack(Blocks.BLUE_CANDLE), new ItemStack(Blocks.BROWN_CANDLE), new ItemStack(Blocks.GREEN_CANDLE),
						new ItemStack(Blocks.RED_CANDLE), new ItemStack(Blocks.BLACK_CANDLE), new ItemStack(Blocks.LIGHT),
						new ItemStack(Blocks.SPAWNER), new ItemStack(Blocks.OAK_STAIRS), new ItemStack(Blocks.SPRUCE_STAIRS),
						new ItemStack(Blocks.BIRCH_STAIRS), new ItemStack(Blocks.JUNGLE_STAIRS), new ItemStack(Blocks.ACACIA_STAIRS),
						new ItemStack(Blocks.DARK_OAK_STAIRS), new ItemStack(Blocks.CRIMSON_STAIRS), new ItemStack(Blocks.WARPED_STAIRS),
						new ItemStack(Blocks.COBBLESTONE_STAIRS), new ItemStack(Blocks.BRICK_STAIRS), new ItemStack(Blocks.STONE_BRICK_STAIRS),
						new ItemStack(Blocks.NETHER_BRICK_STAIRS), new ItemStack(Blocks.QUARTZ_STAIRS), new ItemStack(Blocks.PURPUR_STAIRS),
						new ItemStack(Blocks.CHEST), new ItemStack(Blocks.TRAPPED_CHEST), new ItemStack(Blocks.ENDER_CHEST),
						new ItemStack(Blocks.CRAFTING_TABLE), new ItemStack(Blocks.WHEAT), new ItemStack(Blocks.FARMLAND),
						new ItemStack(Blocks.FURNACE), new ItemStack(Blocks.OAK_SIGN), new ItemStack(Blocks.SPRUCE_SIGN),
						new ItemStack(Blocks.BIRCH_SIGN), new ItemStack(Blocks.ACACIA_SIGN), new ItemStack(Blocks.JUNGLE_SIGN),
						new ItemStack(Blocks.DARK_OAK_SIGN), new ItemStack(Blocks.CRIMSON_SIGN), new ItemStack(Blocks.WARPED_SIGN),
						new ItemStack(Blocks.OAK_WALL_SIGN), new ItemStack(Blocks.SPRUCE_WALL_SIGN), new ItemStack(Blocks.BIRCH_WALL_SIGN),
						new ItemStack(Blocks.ACACIA_WALL_SIGN), new ItemStack(Blocks.JUNGLE_WALL_SIGN), new ItemStack(Blocks.DARK_OAK_WALL_SIGN),
						new ItemStack(Blocks.CRIMSON_WALL_SIGN), new ItemStack(Blocks.WARPED_WALL_SIGN), new ItemStack(Blocks.OAK_DOOR),
						new ItemStack(Blocks.SPRUCE_DOOR), new ItemStack(Blocks.BIRCH_DOOR), new ItemStack(Blocks.JUNGLE_DOOR),
						new ItemStack(Blocks.ACACIA_DOOR), new ItemStack(Blocks.DARK_OAK_DOOR), new ItemStack(Blocks.CRIMSON_DOOR),
						new ItemStack(Blocks.WARPED_DOOR), new ItemStack(Blocks.IRON_DOOR), new ItemStack(Blocks.OAK_TRAPDOOR),
						new ItemStack(Blocks.SPRUCE_TRAPDOOR), new ItemStack(Blocks.BIRCH_TRAPDOOR), new ItemStack(Blocks.JUNGLE_TRAPDOOR),
						new ItemStack(Blocks.ACACIA_TRAPDOOR), new ItemStack(Blocks.DARK_OAK_TRAPDOOR), new ItemStack(Blocks.CRIMSON_TRAPDOOR),
						new ItemStack(Blocks.WARPED_TRAPDOOR), new ItemStack(Blocks.IRON_TRAPDOOR), new ItemStack(Blocks.LADDER),
						new ItemStack(Blocks.LEVER), new ItemStack(Blocks.STONE_BUTTON), new ItemStack(Blocks.POLISHED_BLACKSTONE_BUTTON),
						new ItemStack(Blocks.OAK_BUTTON), new ItemStack(Blocks.SPRUCE_BUTTON), new ItemStack(Blocks.BIRCH_BUTTON),
						new ItemStack(Blocks.JUNGLE_BUTTON), new ItemStack(Blocks.ACACIA_BUTTON), new ItemStack(Blocks.DARK_OAK_BUTTON),
						new ItemStack(Blocks.CRIMSON_BUTTON), new ItemStack(Blocks.WARPED_BUTTON), new ItemStack(Blocks.OAK_PRESSURE_PLATE),
						new ItemStack(Blocks.SPRUCE_PRESSURE_PLATE), new ItemStack(Blocks.BIRCH_PRESSURE_PLATE),
						new ItemStack(Blocks.JUNGLE_PRESSURE_PLATE), new ItemStack(Blocks.ACACIA_PRESSURE_PLATE),
						new ItemStack(Blocks.DARK_OAK_PRESSURE_PLATE), new ItemStack(Blocks.CRIMSON_PRESSURE_PLATE),
						new ItemStack(Blocks.WARPED_PRESSURE_PLATE), new ItemStack(Blocks.STONE_PRESSURE_PLATE),
						new ItemStack(Blocks.POLISHED_BLACKSTONE_PRESSURE_PLATE), new ItemStack(Blocks.LIGHT_WEIGHTED_PRESSURE_PLATE),
						new ItemStack(Blocks.HEAVY_WEIGHTED_PRESSURE_PLATE), new ItemStack(Blocks.TRIPWIRE_HOOK), new ItemStack(Blocks.TRIPWIRE),
						new ItemStack(Blocks.DAYLIGHT_DETECTOR), new ItemStack(Blocks.DAYLIGHT_DETECTOR), new ItemStack(Blocks.REDSTONE_TORCH),
						new ItemStack(Blocks.REDSTONE_WALL_TORCH), new ItemStack(Blocks.REDSTONE_TORCH), new ItemStack(Blocks.REDSTONE_WIRE),
						new ItemStack(Blocks.REPEATER), new ItemStack(Blocks.REPEATER), new ItemStack(Blocks.COMPARATOR),
						new ItemStack(Blocks.COMPARATOR), new ItemStack(Blocks.REDSTONE_LAMP), new ItemStack(Blocks.REDSTONE_LAMP),
						new ItemStack(Blocks.DISPENSER), new ItemStack(Blocks.DROPPER), new ItemStack(Blocks.OBSERVER), new ItemStack(Blocks.HOPPER),
						new ItemStack(Blocks.TARGET), new ItemStack(Blocks.LIGHTNING_ROD), new ItemStack(Blocks.SCULK_SENSOR),
						new ItemStack(Blocks.COMMAND_BLOCK), new ItemStack(Blocks.REPEATING_COMMAND_BLOCK), new ItemStack(Blocks.CHAIN_COMMAND_BLOCK),
						new ItemStack(Blocks.SNOW), new ItemStack(Blocks.SNOW_BLOCK), new ItemStack(Blocks.POWDER_SNOW), new ItemStack(Blocks.ICE),
						new ItemStack(Blocks.PACKED_ICE), new ItemStack(Blocks.FROSTED_ICE), new ItemStack(Blocks.BLUE_ICE),
						new ItemStack(Blocks.CACTUS), new ItemStack(Blocks.CLAY), new ItemStack(Blocks.JUKEBOX), new ItemStack(Blocks.OAK_FENCE),
						new ItemStack(Blocks.SPRUCE_FENCE), new ItemStack(Blocks.BIRCH_FENCE), new ItemStack(Blocks.JUNGLE_FENCE),
						new ItemStack(Blocks.ACACIA_FENCE), new ItemStack(Blocks.DARK_OAK_FENCE), new ItemStack(Blocks.CRIMSON_FENCE),
						new ItemStack(Blocks.WARPED_FENCE), new ItemStack(Blocks.OAK_FENCE_GATE), new ItemStack(Blocks.SPRUCE_FENCE_GATE),
						new ItemStack(Blocks.BIRCH_FENCE_GATE), new ItemStack(Blocks.JUNGLE_FENCE_GATE), new ItemStack(Blocks.ACACIA_FENCE_GATE),
						new ItemStack(Blocks.DARK_OAK_FENCE_GATE), new ItemStack(Blocks.CRIMSON_FENCE_GATE), new ItemStack(Blocks.WARPED_FENCE_GATE),
						new ItemStack(Blocks.NETHER_BRICK_FENCE), new ItemStack(Blocks.NETHER_BRICKS), new ItemStack(Blocks.CHISELED_NETHER_BRICKS),
						new ItemStack(Blocks.CRACKED_NETHER_BRICKS), new ItemStack(Blocks.RED_NETHER_BRICKS), new ItemStack(Blocks.NETHER_BRICK_WALL),
						new ItemStack(Blocks.RED_NETHER_BRICK_STAIRS), new ItemStack(Blocks.RED_NETHER_BRICK_SLAB),
						new ItemStack(Blocks.RED_NETHER_BRICK_WALL), new ItemStack(Blocks.NETHERRACK), new ItemStack(Blocks.WARPED_NYLIUM),
						new ItemStack(Blocks.CRIMSON_NYLIUM), new ItemStack(Blocks.SOUL_SAND), new ItemStack(Blocks.SOUL_SOIL),
						new ItemStack(Blocks.GLOWSTONE), new ItemStack(Blocks.SHROOMLIGHT), new ItemStack(Blocks.BONE_BLOCK),
						new ItemStack(Blocks.NETHER_WART), new ItemStack(Blocks.NETHER_WART_BLOCK), new ItemStack(Blocks.CAKE),
						new ItemStack(Blocks.STONE_BRICKS), new ItemStack(Blocks.STONE_BRICK_WALL), new ItemStack(Blocks.MOSSY_STONE_BRICKS),
						new ItemStack(Blocks.MOSSY_STONE_BRICK_STAIRS), new ItemStack(Blocks.MOSSY_STONE_BRICK_SLAB),
						new ItemStack(Blocks.MOSSY_STONE_BRICK_WALL), new ItemStack(Blocks.CRACKED_STONE_BRICKS),
						new ItemStack(Blocks.CHISELED_STONE_BRICKS), new ItemStack(Blocks.IRON_BARS), new ItemStack(Blocks.MELON),
						new ItemStack(Blocks.MELON_STEM), new ItemStack(Blocks.ATTACHED_MELON_STEM), new ItemStack(Blocks.PUMPKIN),
						new ItemStack(Blocks.CARVED_PUMPKIN), new ItemStack(Blocks.JACK_O_LANTERN), new ItemStack(Blocks.PUMPKIN_STEM),
						new ItemStack(Blocks.ATTACHED_PUMPKIN_STEM), new ItemStack(Blocks.SWEET_BERRY_BUSH), new ItemStack(Blocks.VINE),
						new ItemStack(Blocks.GLOW_LICHEN), new ItemStack(Blocks.LILY_PAD), new ItemStack(Blocks.ENCHANTING_TABLE),
						new ItemStack(Blocks.BREWING_STAND), new ItemStack(Blocks.CAULDRON), new ItemStack(Blocks.WATER_CAULDRON),
						new ItemStack(Blocks.LAVA_CAULDRON), new ItemStack(Blocks.POWDER_SNOW_CAULDRON), new ItemStack(Blocks.END_PORTAL),
						new ItemStack(Blocks.END_PORTAL_FRAME), new ItemStack(Blocks.END_GATEWAY), new ItemStack(Blocks.END_STONE),
						new ItemStack(Blocks.END_STONE_BRICKS), new ItemStack(Blocks.END_STONE_BRICK_STAIRS),
						new ItemStack(Blocks.END_STONE_BRICK_SLAB), new ItemStack(Blocks.END_STONE_BRICK_WALL), new ItemStack(Blocks.END_ROD),
						new ItemStack(Blocks.PURPUR_BLOCK), new ItemStack(Blocks.PURPUR_PILLAR), new ItemStack(Blocks.PURPUR_SLAB),
						new ItemStack(Blocks.PURPUR_SLAB), new ItemStack(Blocks.BEETROOTS), new ItemStack(Blocks.CHORUS_PLANT),
						new ItemStack(Blocks.CHORUS_FLOWER), new ItemStack(Blocks.DRAGON_EGG), new ItemStack(Blocks.INFESTED_STONE),
						new ItemStack(Blocks.INFESTED_COBBLESTONE), new ItemStack(Blocks.INFESTED_STONE_BRICKS),
						new ItemStack(Blocks.INFESTED_MOSSY_STONE_BRICKS), new ItemStack(Blocks.INFESTED_CRACKED_STONE_BRICKS),
						new ItemStack(Blocks.INFESTED_CHISELED_STONE_BRICKS), new ItemStack(Blocks.INFESTED_DEEPSLATE),
						new ItemStack(Blocks.OAK_SLAB), new ItemStack(Blocks.SPRUCE_SLAB), new ItemStack(Blocks.BIRCH_SLAB),
						new ItemStack(Blocks.JUNGLE_SLAB), new ItemStack(Blocks.ACACIA_SLAB), new ItemStack(Blocks.DARK_OAK_SLAB),
						new ItemStack(Blocks.CRIMSON_SLAB), new ItemStack(Blocks.WARPED_SLAB), new ItemStack(Blocks.SMOOTH_STONE_SLAB),
						new ItemStack(Blocks.SANDSTONE_SLAB), new ItemStack(Blocks.PETRIFIED_OAK_SLAB), new ItemStack(Blocks.COBBLESTONE_SLAB),
						new ItemStack(Blocks.BRICK_SLAB), new ItemStack(Blocks.STONE_BRICK_SLAB), new ItemStack(Blocks.NETHER_BRICK_SLAB),
						new ItemStack(Blocks.QUARTZ_SLAB), new ItemStack(Blocks.RED_SANDSTONE_SLAB), new ItemStack(Blocks.COCOA),
						new ItemStack(Blocks.NETHER_PORTAL), new ItemStack(Blocks.ANVIL), new ItemStack(Blocks.CHIPPED_ANVIL),
						new ItemStack(Blocks.DAMAGED_ANVIL), new ItemStack(Blocks.BEACON), new ItemStack(Blocks.COBBLESTONE_WALL),
						new ItemStack(Blocks.MOSSY_COBBLESTONE_WALL), new ItemStack(Blocks.FLOWER_POT), new ItemStack(Blocks.POTTED_OAK_SAPLING),
						new ItemStack(Blocks.POTTED_SPRUCE_SAPLING), new ItemStack(Blocks.POTTED_BIRCH_SAPLING),
						new ItemStack(Blocks.POTTED_JUNGLE_SAPLING), new ItemStack(Blocks.POTTED_ACACIA_SAPLING),
						new ItemStack(Blocks.POTTED_DARK_OAK_SAPLING), new ItemStack(Blocks.POTTED_FERN), new ItemStack(Blocks.POTTED_DANDELION),
						new ItemStack(Blocks.POTTED_POPPY), new ItemStack(Blocks.POTTED_BLUE_ORCHID), new ItemStack(Blocks.POTTED_ALLIUM),
						new ItemStack(Blocks.POTTED_AZURE_BLUET), new ItemStack(Blocks.POTTED_RED_TULIP), new ItemStack(Blocks.POTTED_ORANGE_TULIP),
						new ItemStack(Blocks.POTTED_WHITE_TULIP), new ItemStack(Blocks.POTTED_PINK_TULIP), new ItemStack(Blocks.POTTED_OXEYE_DAISY),
						new ItemStack(Blocks.POTTED_CORNFLOWER), new ItemStack(Blocks.POTTED_LILY_OF_THE_VALLEY),
						new ItemStack(Blocks.POTTED_WITHER_ROSE), new ItemStack(Blocks.POTTED_RED_MUSHROOM),
						new ItemStack(Blocks.POTTED_BROWN_MUSHROOM), new ItemStack(Blocks.POTTED_DEAD_BUSH), new ItemStack(Blocks.POTTED_CACTUS),
						new ItemStack(Blocks.POTTED_BAMBOO), new ItemStack(Blocks.POTTED_CRIMSON_FUNGUS), new ItemStack(Blocks.POTTED_WARPED_FUNGUS),
						new ItemStack(Blocks.POTTED_CRIMSON_ROOTS), new ItemStack(Blocks.POTTED_WARPED_ROOTS), new ItemStack(Blocks.POTTED_AZALEA),
						new ItemStack(Blocks.POTTED_FLOWERING_AZALEA), new ItemStack(Blocks.CARROTS), new ItemStack(Blocks.POTATOES),
						new ItemStack(Blocks.HAY_BLOCK), new ItemStack(Blocks.SKELETON_SKULL), new ItemStack(Blocks.WITHER_SKELETON_SKULL),
						new ItemStack(Blocks.ZOMBIE_HEAD), new ItemStack(Blocks.PLAYER_HEAD), new ItemStack(Blocks.CREEPER_HEAD),
						new ItemStack(Blocks.DRAGON_HEAD), new ItemStack(Blocks.SKELETON_WALL_SKULL),
						new ItemStack(Blocks.WITHER_SKELETON_WALL_SKULL), new ItemStack(Blocks.ZOMBIE_WALL_HEAD),
						new ItemStack(Blocks.PLAYER_WALL_HEAD), new ItemStack(Blocks.CREEPER_WALL_HEAD), new ItemStack(Blocks.DRAGON_WALL_HEAD),
						new ItemStack(Blocks.WHITE_WOOL), new ItemStack(Blocks.ORANGE_WOOL), new ItemStack(Blocks.MAGENTA_WOOL),
						new ItemStack(Blocks.LIGHT_BLUE_WOOL), new ItemStack(Blocks.YELLOW_WOOL), new ItemStack(Blocks.LIME_WOOL),
						new ItemStack(Blocks.PINK_WOOL), new ItemStack(Blocks.GRAY_WOOL), new ItemStack(Blocks.LIGHT_GRAY_WOOL),
						new ItemStack(Blocks.CYAN_WOOL), new ItemStack(Blocks.PURPLE_WOOL), new ItemStack(Blocks.BLUE_WOOL),
						new ItemStack(Blocks.BROWN_WOOL), new ItemStack(Blocks.GREEN_WOOL), new ItemStack(Blocks.RED_WOOL),
						new ItemStack(Blocks.BLACK_WOOL), new ItemStack(Blocks.TERRACOTTA), new ItemStack(Blocks.WHITE_TERRACOTTA),
						new ItemStack(Blocks.ORANGE_TERRACOTTA), new ItemStack(Blocks.MAGENTA_TERRACOTTA),
						new ItemStack(Blocks.LIGHT_BLUE_TERRACOTTA), new ItemStack(Blocks.YELLOW_TERRACOTTA), new ItemStack(Blocks.LIME_TERRACOTTA),
						new ItemStack(Blocks.PINK_TERRACOTTA), new ItemStack(Blocks.GRAY_TERRACOTTA), new ItemStack(Blocks.LIGHT_GRAY_TERRACOTTA),
						new ItemStack(Blocks.CYAN_TERRACOTTA), new ItemStack(Blocks.PURPLE_TERRACOTTA), new ItemStack(Blocks.BLUE_TERRACOTTA),
						new ItemStack(Blocks.BROWN_TERRACOTTA), new ItemStack(Blocks.GREEN_TERRACOTTA), new ItemStack(Blocks.RED_TERRACOTTA),
						new ItemStack(Blocks.BLACK_TERRACOTTA), new ItemStack(Blocks.WHITE_GLAZED_TERRACOTTA),
						new ItemStack(Blocks.ORANGE_GLAZED_TERRACOTTA), new ItemStack(Blocks.MAGENTA_GLAZED_TERRACOTTA),
						new ItemStack(Blocks.LIGHT_BLUE_GLAZED_TERRACOTTA), new ItemStack(Blocks.YELLOW_GLAZED_TERRACOTTA),
						new ItemStack(Blocks.LIME_GLAZED_TERRACOTTA), new ItemStack(Blocks.PINK_GLAZED_TERRACOTTA),
						new ItemStack(Blocks.GRAY_GLAZED_TERRACOTTA), new ItemStack(Blocks.LIGHT_GRAY_GLAZED_TERRACOTTA),
						new ItemStack(Blocks.CYAN_GLAZED_TERRACOTTA), new ItemStack(Blocks.PURPLE_GLAZED_TERRACOTTA),
						new ItemStack(Blocks.BLUE_GLAZED_TERRACOTTA), new ItemStack(Blocks.BROWN_GLAZED_TERRACOTTA),
						new ItemStack(Blocks.GREEN_GLAZED_TERRACOTTA), new ItemStack(Blocks.RED_GLAZED_TERRACOTTA),
						new ItemStack(Blocks.BLACK_GLAZED_TERRACOTTA), new ItemStack(Blocks.WHITE_CONCRETE_POWDER),
						new ItemStack(Blocks.ORANGE_CONCRETE_POWDER), new ItemStack(Blocks.MAGENTA_CONCRETE_POWDER),
						new ItemStack(Blocks.LIGHT_BLUE_CONCRETE_POWDER), new ItemStack(Blocks.YELLOW_CONCRETE_POWDER),
						new ItemStack(Blocks.LIME_CONCRETE_POWDER), new ItemStack(Blocks.PINK_CONCRETE_POWDER),
						new ItemStack(Blocks.GRAY_CONCRETE_POWDER), new ItemStack(Blocks.LIGHT_GRAY_CONCRETE_POWDER),
						new ItemStack(Blocks.CYAN_CONCRETE_POWDER), new ItemStack(Blocks.PURPLE_CONCRETE_POWDER),
						new ItemStack(Blocks.BLUE_CONCRETE_POWDER), new ItemStack(Blocks.BROWN_CONCRETE_POWDER),
						new ItemStack(Blocks.GREEN_CONCRETE_POWDER), new ItemStack(Blocks.RED_CONCRETE_POWDER),
						new ItemStack(Blocks.BLACK_CONCRETE_POWDER), new ItemStack(Blocks.WHITE_CONCRETE), new ItemStack(Blocks.ORANGE_CONCRETE),
						new ItemStack(Blocks.MAGENTA_CONCRETE), new ItemStack(Blocks.LIGHT_BLUE_CONCRETE), new ItemStack(Blocks.YELLOW_CONCRETE),
						new ItemStack(Blocks.LIME_CONCRETE), new ItemStack(Blocks.PINK_CONCRETE), new ItemStack(Blocks.GRAY_CONCRETE),
						new ItemStack(Blocks.LIGHT_GRAY_CONCRETE), new ItemStack(Blocks.CYAN_CONCRETE), new ItemStack(Blocks.PURPLE_CONCRETE),
						new ItemStack(Blocks.BLUE_CONCRETE), new ItemStack(Blocks.BROWN_CONCRETE), new ItemStack(Blocks.GREEN_CONCRETE),
						new ItemStack(Blocks.RED_CONCRETE), new ItemStack(Blocks.BLACK_CONCRETE), new ItemStack(Blocks.WHITE_CARPET),
						new ItemStack(Blocks.ORANGE_CARPET), new ItemStack(Blocks.MAGENTA_CARPET), new ItemStack(Blocks.LIGHT_BLUE_CARPET),
						new ItemStack(Blocks.YELLOW_CARPET), new ItemStack(Blocks.LIME_CARPET), new ItemStack(Blocks.PINK_CARPET),
						new ItemStack(Blocks.GRAY_CARPET), new ItemStack(Blocks.LIGHT_GRAY_CARPET), new ItemStack(Blocks.CYAN_CARPET),
						new ItemStack(Blocks.PURPLE_CARPET), new ItemStack(Blocks.BLUE_CARPET), new ItemStack(Blocks.BROWN_CARPET),
						new ItemStack(Blocks.GREEN_CARPET), new ItemStack(Blocks.RED_CARPET), new ItemStack(Blocks.BLACK_CARPET),
						new ItemStack(Blocks.GLASS), new ItemStack(Blocks.TINTED_GLASS), new ItemStack(Blocks.WHITE_STAINED_GLASS),
						new ItemStack(Blocks.ORANGE_STAINED_GLASS), new ItemStack(Blocks.MAGENTA_STAINED_GLASS),
						new ItemStack(Blocks.LIGHT_BLUE_STAINED_GLASS), new ItemStack(Blocks.YELLOW_STAINED_GLASS),
						new ItemStack(Blocks.LIME_STAINED_GLASS), new ItemStack(Blocks.PINK_STAINED_GLASS), new ItemStack(Blocks.GRAY_STAINED_GLASS),
						new ItemStack(Blocks.LIGHT_GRAY_STAINED_GLASS), new ItemStack(Blocks.CYAN_STAINED_GLASS),
						new ItemStack(Blocks.PURPLE_STAINED_GLASS), new ItemStack(Blocks.BLUE_STAINED_GLASS),
						new ItemStack(Blocks.BROWN_STAINED_GLASS), new ItemStack(Blocks.GREEN_STAINED_GLASS), new ItemStack(Blocks.RED_STAINED_GLASS),
						new ItemStack(Blocks.BLACK_STAINED_GLASS), new ItemStack(Blocks.GLASS_PANE), new ItemStack(Blocks.WHITE_STAINED_GLASS_PANE),
						new ItemStack(Blocks.ORANGE_STAINED_GLASS_PANE), new ItemStack(Blocks.MAGENTA_STAINED_GLASS_PANE),
						new ItemStack(Blocks.LIGHT_BLUE_STAINED_GLASS_PANE), new ItemStack(Blocks.YELLOW_STAINED_GLASS_PANE),
						new ItemStack(Blocks.LIME_STAINED_GLASS_PANE), new ItemStack(Blocks.PINK_STAINED_GLASS_PANE),
						new ItemStack(Blocks.GRAY_STAINED_GLASS_PANE), new ItemStack(Blocks.LIGHT_GRAY_STAINED_GLASS_PANE),
						new ItemStack(Blocks.CYAN_STAINED_GLASS_PANE), new ItemStack(Blocks.PURPLE_STAINED_GLASS_PANE),
						new ItemStack(Blocks.BLUE_STAINED_GLASS_PANE), new ItemStack(Blocks.BROWN_STAINED_GLASS_PANE),
						new ItemStack(Blocks.GREEN_STAINED_GLASS_PANE), new ItemStack(Blocks.RED_STAINED_GLASS_PANE),
						new ItemStack(Blocks.BLACK_STAINED_GLASS_PANE), new ItemStack(Blocks.SEA_LANTERN), new ItemStack(Blocks.PRISMARINE),
						new ItemStack(Blocks.PRISMARINE_BRICKS), new ItemStack(Blocks.DARK_PRISMARINE), new ItemStack(Blocks.PRISMARINE_STAIRS),
						new ItemStack(Blocks.PRISMARINE_BRICK_STAIRS), new ItemStack(Blocks.DARK_PRISMARINE_STAIRS),
						new ItemStack(Blocks.PRISMARINE_SLAB), new ItemStack(Blocks.PRISMARINE_BRICK_SLAB),
						new ItemStack(Blocks.DARK_PRISMARINE_SLAB), new ItemStack(Blocks.PRISMARINE_WALL), new ItemStack(Blocks.SHULKER_BOX),
						new ItemStack(Blocks.WHITE_SHULKER_BOX), new ItemStack(Blocks.ORANGE_SHULKER_BOX), new ItemStack(Blocks.MAGENTA_SHULKER_BOX),
						new ItemStack(Blocks.LIGHT_BLUE_SHULKER_BOX), new ItemStack(Blocks.YELLOW_SHULKER_BOX),
						new ItemStack(Blocks.LIME_SHULKER_BOX), new ItemStack(Blocks.PINK_SHULKER_BOX), new ItemStack(Blocks.GRAY_SHULKER_BOX),
						new ItemStack(Blocks.LIGHT_GRAY_SHULKER_BOX), new ItemStack(Blocks.CYAN_SHULKER_BOX),
						new ItemStack(Blocks.PURPLE_SHULKER_BOX), new ItemStack(Blocks.BLUE_SHULKER_BOX), new ItemStack(Blocks.BROWN_SHULKER_BOX),
						new ItemStack(Blocks.GREEN_SHULKER_BOX), new ItemStack(Blocks.RED_SHULKER_BOX), new ItemStack(Blocks.BLACK_SHULKER_BOX),
						new ItemStack(Blocks.WHITE_BANNER), new ItemStack(Blocks.WHITE_BANNER), new ItemStack(Blocks.ORANGE_BANNER),
						new ItemStack(Blocks.MAGENTA_BANNER), new ItemStack(Blocks.LIGHT_BLUE_BANNER), new ItemStack(Blocks.YELLOW_BANNER),
						new ItemStack(Blocks.LIME_BANNER), new ItemStack(Blocks.PINK_BANNER), new ItemStack(Blocks.GRAY_BANNER),
						new ItemStack(Blocks.LIGHT_GRAY_BANNER), new ItemStack(Blocks.CYAN_BANNER), new ItemStack(Blocks.PURPLE_BANNER),
						new ItemStack(Blocks.BLUE_BANNER), new ItemStack(Blocks.BROWN_BANNER), new ItemStack(Blocks.GREEN_BANNER),
						new ItemStack(Blocks.RED_BANNER), new ItemStack(Blocks.BLACK_BANNER), new ItemStack(Blocks.WHITE_WALL_BANNER),
						new ItemStack(Blocks.WHITE_WALL_BANNER), new ItemStack(Blocks.ORANGE_WALL_BANNER), new ItemStack(Blocks.MAGENTA_WALL_BANNER),
						new ItemStack(Blocks.LIGHT_BLUE_WALL_BANNER), new ItemStack(Blocks.YELLOW_WALL_BANNER),
						new ItemStack(Blocks.LIME_WALL_BANNER), new ItemStack(Blocks.PINK_WALL_BANNER), new ItemStack(Blocks.GRAY_WALL_BANNER),
						new ItemStack(Blocks.LIGHT_GRAY_WALL_BANNER), new ItemStack(Blocks.CYAN_WALL_BANNER),
						new ItemStack(Blocks.PURPLE_WALL_BANNER), new ItemStack(Blocks.BLUE_WALL_BANNER), new ItemStack(Blocks.BROWN_WALL_BANNER),
						new ItemStack(Blocks.GREEN_WALL_BANNER), new ItemStack(Blocks.RED_WALL_BANNER), new ItemStack(Blocks.BLACK_WALL_BANNER),
						new ItemStack(Blocks.BARRIER), new ItemStack(Blocks.STRUCTURE_VOID), new ItemStack(Blocks.STRUCTURE_BLOCK),
						new ItemStack(Blocks.STRUCTURE_BLOCK), new ItemStack(Blocks.STRUCTURE_BLOCK), new ItemStack(Blocks.STRUCTURE_BLOCK),
						new ItemStack(Blocks.STRUCTURE_BLOCK), new ItemStack(Blocks.JIGSAW), new ItemStack(Blocks.KELP),
						new ItemStack(Blocks.KELP_PLANT), new ItemStack(Blocks.SEAGRASS), new ItemStack(Blocks.TALL_SEAGRASS),
						new ItemStack(Blocks.SEA_PICKLE), new ItemStack(Blocks.TURTLE_EGG), new ItemStack(Blocks.BAMBOO_SAPLING),
						new ItemStack(Blocks.BAMBOO), new ItemStack(Blocks.DEAD_TUBE_CORAL_BLOCK), new ItemStack(Blocks.DEAD_BRAIN_CORAL_BLOCK),
						new ItemStack(Blocks.DEAD_BUBBLE_CORAL_BLOCK), new ItemStack(Blocks.DEAD_FIRE_CORAL_BLOCK),
						new ItemStack(Blocks.DEAD_HORN_CORAL_BLOCK), new ItemStack(Blocks.TUBE_CORAL_BLOCK), new ItemStack(Blocks.BRAIN_CORAL_BLOCK),
						new ItemStack(Blocks.BUBBLE_CORAL_BLOCK), new ItemStack(Blocks.FIRE_CORAL_BLOCK), new ItemStack(Blocks.HORN_CORAL_BLOCK),
						new ItemStack(Blocks.DEAD_TUBE_CORAL), new ItemStack(Blocks.DEAD_BRAIN_CORAL), new ItemStack(Blocks.DEAD_BUBBLE_CORAL),
						new ItemStack(Blocks.DEAD_FIRE_CORAL), new ItemStack(Blocks.DEAD_HORN_CORAL), new ItemStack(Blocks.TUBE_CORAL),
						new ItemStack(Blocks.BRAIN_CORAL), new ItemStack(Blocks.BUBBLE_CORAL), new ItemStack(Blocks.FIRE_CORAL),
						new ItemStack(Blocks.HORN_CORAL), new ItemStack(Blocks.DEAD_TUBE_CORAL_FAN), new ItemStack(Blocks.DEAD_BRAIN_CORAL_FAN),
						new ItemStack(Blocks.DEAD_BUBBLE_CORAL_FAN), new ItemStack(Blocks.DEAD_FIRE_CORAL_FAN),
						new ItemStack(Blocks.DEAD_HORN_CORAL_FAN), new ItemStack(Blocks.TUBE_CORAL_FAN), new ItemStack(Blocks.BRAIN_CORAL_FAN),
						new ItemStack(Blocks.BUBBLE_CORAL_FAN), new ItemStack(Blocks.FIRE_CORAL_FAN), new ItemStack(Blocks.HORN_CORAL_FAN),
						new ItemStack(Blocks.DEAD_TUBE_CORAL_WALL_FAN), new ItemStack(Blocks.DEAD_BRAIN_CORAL_WALL_FAN),
						new ItemStack(Blocks.DEAD_BUBBLE_CORAL_WALL_FAN), new ItemStack(Blocks.DEAD_FIRE_CORAL_WALL_FAN),
						new ItemStack(Blocks.DEAD_HORN_CORAL_WALL_FAN), new ItemStack(Blocks.TUBE_CORAL_WALL_FAN),
						new ItemStack(Blocks.BRAIN_CORAL_WALL_FAN), new ItemStack(Blocks.BUBBLE_CORAL_WALL_FAN),
						new ItemStack(Blocks.FIRE_CORAL_WALL_FAN), new ItemStack(Blocks.HORN_CORAL_WALL_FAN), new ItemStack(Blocks.DRIED_KELP_BLOCK),
						new ItemStack(Blocks.CONDUIT), new ItemStack(Blocks.SCAFFOLDING), new ItemStack(Blocks.BELL), new ItemStack(Blocks.LOOM),
						new ItemStack(Blocks.BARREL), new ItemStack(Blocks.SMOKER), new ItemStack(Blocks.BLAST_FURNACE),
						new ItemStack(Blocks.CARTOGRAPHY_TABLE), new ItemStack(Blocks.FLETCHING_TABLE), new ItemStack(Blocks.GRINDSTONE),
						new ItemStack(Blocks.LECTERN), new ItemStack(Blocks.SMITHING_TABLE), new ItemStack(Blocks.STONECUTTER),
						new ItemStack(Blocks.COMPOSTER), new ItemStack(Blocks.BEEHIVE), new ItemStack(Blocks.BEE_NEST),
						new ItemStack(Blocks.HONEY_BLOCK), new ItemStack(Blocks.HONEYCOMB_BLOCK), new ItemStack(Blocks.BASALT),
						new ItemStack(Blocks.POLISHED_BASALT), new ItemStack(Blocks.SMOOTH_BASALT), new ItemStack(Blocks.WARPED_ROOTS),
						new ItemStack(Blocks.NETHER_SPROUTS), new ItemStack(Blocks.WEEPING_VINES), new ItemStack(Blocks.WEEPING_VINES_PLANT),
						new ItemStack(Blocks.TWISTING_VINES), new ItemStack(Blocks.TWISTING_VINES_PLANT), new ItemStack(Blocks.CRIMSON_ROOTS),
						new ItemStack(Blocks.RESPAWN_ANCHOR), new ItemStack(Blocks.LODESTONE), new ItemStack(Blocks.CAVE_VINES),
						new ItemStack(Blocks.CAVE_VINES_PLANT), new ItemStack(Blocks.SPORE_BLOSSOM), new ItemStack(Blocks.AZALEA),
						new ItemStack(Blocks.FLOWERING_AZALEA), new ItemStack(Blocks.BIG_DRIPLEAF), new ItemStack(Blocks.BIG_DRIPLEAF_STEM),
						new ItemStack(Blocks.SMALL_DRIPLEAF), new ItemStack(Blocks.HANGING_ROOTS), new ItemStack(Items.INK_SAC),
						new ItemStack(Items.GLOW_INK_SAC), new ItemStack(Items.RED_DYE), new ItemStack(Items.GREEN_DYE),
						new ItemStack(Items.COCOA_BEANS), new ItemStack(Items.LAPIS_LAZULI), new ItemStack(Items.PURPLE_DYE),
						new ItemStack(Items.CYAN_DYE), new ItemStack(Items.LIGHT_GRAY_DYE), new ItemStack(Items.GRAY_DYE),
						new ItemStack(Items.PINK_DYE), new ItemStack(Items.LIME_DYE), new ItemStack(Items.YELLOW_DYE),
						new ItemStack(Items.LIGHT_BLUE_DYE), new ItemStack(Items.MAGENTA_DYE), new ItemStack(Items.ORANGE_DYE),
						new ItemStack(Items.BONE_MEAL), new ItemStack(Items.BLACK_DYE), new ItemStack(Items.BROWN_DYE), new ItemStack(Items.BLUE_DYE),
						new ItemStack(Items.WHITE_DYE), new ItemStack(Items.COAL), new ItemStack(Items.CHARCOAL), new ItemStack(Items.RAW_IRON),
						new ItemStack(Items.IRON_INGOT), new ItemStack(Items.IRON_NUGGET), new ItemStack(Items.RAW_COPPER),
						new ItemStack(Items.COPPER_INGOT), new ItemStack(Items.REDSTONE), new ItemStack(Items.RAW_GOLD),
						new ItemStack(Items.GOLD_INGOT), new ItemStack(Items.GOLD_NUGGET), new ItemStack(Items.DIAMOND),
						new ItemStack(Items.NETHERITE_INGOT), new ItemStack(Items.NETHERITE_SCRAP), new ItemStack(Items.EMERALD),
						new ItemStack(Items.QUARTZ), new ItemStack(Items.NETHER_STAR), new ItemStack(Items.PRISMARINE_SHARD),
						new ItemStack(Items.PRISMARINE_CRYSTALS), new ItemStack(Items.HEART_OF_THE_SEA), new ItemStack(Items.NAUTILUS_SHELL),
						new ItemStack(Items.SCUTE), new ItemStack(Items.PHANTOM_MEMBRANE), new ItemStack(Items.AMETHYST_SHARD),
						new ItemStack(Items.BOW), new ItemStack(Items.CROSSBOW), new ItemStack(Items.ARROW), new ItemStack(Items.SPECTRAL_ARROW),
						new ItemStack(Items.TIPPED_ARROW), new ItemStack(Items.FISHING_ROD), new ItemStack(Items.CARROT_ON_A_STICK),
						new ItemStack(Items.WARPED_FUNGUS_ON_A_STICK), new ItemStack(Items.COMPASS), new ItemStack(Items.CLOCK),
						new ItemStack(Items.SPYGLASS), new ItemStack(Items.BUNDLE), new ItemStack(Items.MAP), new ItemStack(Items.FILLED_MAP),
						new ItemStack(Items.FLOWER_BANNER_PATTERN), new ItemStack(Items.CREEPER_BANNER_PATTERN),
						new ItemStack(Items.SKULL_BANNER_PATTERN), new ItemStack(Items.MOJANG_BANNER_PATTERN),
						new ItemStack(Items.GLOBE_BANNER_PATTERN), new ItemStack(Items.PIGLIN_BANNER_PATTERN), new ItemStack(Items.TOTEM_OF_UNDYING),
						new ItemStack(Items.LEAD), new ItemStack(Items.NAME_TAG), new ItemStack(Items.SHIELD), new ItemStack(Items.WOODEN_SWORD),
						new ItemStack(Items.WOODEN_SHOVEL), new ItemStack(Items.WOODEN_PICKAXE), new ItemStack(Items.WOODEN_AXE),
						new ItemStack(Items.WOODEN_HOE), new ItemStack(Items.STONE_SWORD), new ItemStack(Items.STONE_SHOVEL),
						new ItemStack(Items.STONE_PICKAXE), new ItemStack(Items.STONE_AXE), new ItemStack(Items.STONE_HOE),
						new ItemStack(Items.IRON_SWORD), new ItemStack(Items.IRON_SHOVEL), new ItemStack(Items.IRON_PICKAXE),
						new ItemStack(Items.IRON_AXE), new ItemStack(Items.IRON_HOE), new ItemStack(Items.FLINT_AND_STEEL),
						new ItemStack(Items.SHEARS), new ItemStack(Items.GOLDEN_SWORD), new ItemStack(Items.GOLDEN_SHOVEL),
						new ItemStack(Items.GOLDEN_PICKAXE), new ItemStack(Items.GOLDEN_AXE), new ItemStack(Items.GOLDEN_HOE),
						new ItemStack(Items.DIAMOND_SWORD), new ItemStack(Items.DIAMOND_SHOVEL), new ItemStack(Items.DIAMOND_PICKAXE),
						new ItemStack(Items.DIAMOND_AXE), new ItemStack(Items.DIAMOND_HOE), new ItemStack(Items.NETHERITE_SWORD),
						new ItemStack(Items.NETHERITE_SHOVEL), new ItemStack(Items.NETHERITE_PICKAXE), new ItemStack(Items.NETHERITE_AXE),
						new ItemStack(Items.NETHERITE_HOE), new ItemStack(Items.TRIDENT), new ItemStack(Items.LEATHER_HELMET),
						new ItemStack(Items.LEATHER_CHESTPLATE), new ItemStack(Items.LEATHER_LEGGINGS), new ItemStack(Items.LEATHER_BOOTS),
						new ItemStack(Items.CHAINMAIL_HELMET), new ItemStack(Items.CHAINMAIL_CHESTPLATE), new ItemStack(Items.CHAINMAIL_LEGGINGS),
						new ItemStack(Items.CHAINMAIL_BOOTS), new ItemStack(Items.TURTLE_HELMET), new ItemStack(Items.IRON_HELMET),
						new ItemStack(Items.IRON_CHESTPLATE), new ItemStack(Items.IRON_LEGGINGS), new ItemStack(Items.IRON_BOOTS),
						new ItemStack(Items.GOLDEN_HELMET), new ItemStack(Items.GOLDEN_CHESTPLATE), new ItemStack(Items.GOLDEN_LEGGINGS),
						new ItemStack(Items.GOLDEN_BOOTS), new ItemStack(Items.DIAMOND_HELMET), new ItemStack(Items.DIAMOND_CHESTPLATE),
						new ItemStack(Items.DIAMOND_LEGGINGS), new ItemStack(Items.DIAMOND_BOOTS), new ItemStack(Items.NETHERITE_HELMET),
						new ItemStack(Items.NETHERITE_CHESTPLATE), new ItemStack(Items.NETHERITE_LEGGINGS), new ItemStack(Items.NETHERITE_BOOTS),
						new ItemStack(Items.ELYTRA), new ItemStack(Items.LEATHER_HORSE_ARMOR), new ItemStack(Items.IRON_HORSE_ARMOR),
						new ItemStack(Items.GOLDEN_HORSE_ARMOR), new ItemStack(Items.DIAMOND_HORSE_ARMOR), new ItemStack(Items.ARMOR_STAND),
						new ItemStack(Items.FLOWER_POT), new ItemStack(Items.BLACK_BANNER), new ItemStack(Items.RED_BANNER),
						new ItemStack(Items.GREEN_BANNER), new ItemStack(Items.BROWN_BANNER), new ItemStack(Items.BLUE_BANNER),
						new ItemStack(Items.PURPLE_BANNER), new ItemStack(Items.CYAN_BANNER), new ItemStack(Items.LIGHT_GRAY_BANNER),
						new ItemStack(Items.GRAY_BANNER), new ItemStack(Items.PINK_BANNER), new ItemStack(Items.LIME_BANNER),
						new ItemStack(Items.YELLOW_BANNER), new ItemStack(Items.LIGHT_BLUE_BANNER), new ItemStack(Items.MAGENTA_BANNER),
						new ItemStack(Items.ORANGE_BANNER), new ItemStack(Items.WHITE_BANNER), new ItemStack(Items.PAINTING),
						new ItemStack(Items.ITEM_FRAME), new ItemStack(Items.GLOW_ITEM_FRAME), new ItemStack(Items.OAK_SIGN),
						new ItemStack(Items.SPRUCE_SIGN), new ItemStack(Items.BIRCH_SIGN), new ItemStack(Items.JUNGLE_SIGN),
						new ItemStack(Items.ACACIA_SIGN), new ItemStack(Items.DARK_OAK_SIGN), new ItemStack(Items.CRIMSON_SIGN),
						new ItemStack(Items.WARPED_SIGN), new ItemStack(Items.OAK_DOOR), new ItemStack(Items.SPRUCE_DOOR),
						new ItemStack(Items.BIRCH_DOOR), new ItemStack(Items.JUNGLE_DOOR), new ItemStack(Items.ACACIA_DOOR),
						new ItemStack(Items.DARK_OAK_DOOR), new ItemStack(Items.IRON_DOOR), new ItemStack(Items.CRIMSON_DOOR),
						new ItemStack(Items.WARPED_DOOR), new ItemStack(Items.BUCKET), new ItemStack(Items.WATER_BUCKET),
						new ItemStack(Items.PUFFERFISH_BUCKET), new ItemStack(Items.SALMON_BUCKET), new ItemStack(Items.COD_BUCKET),
						new ItemStack(Items.TROPICAL_FISH_BUCKET), new ItemStack(Items.AXOLOTL_BUCKET), new ItemStack(Items.LAVA_BUCKET),
						new ItemStack(Items.MILK_BUCKET), new ItemStack(Items.POWDER_SNOW_BUCKET), new ItemStack(Items.MINECART),
						new ItemStack(Items.CHEST_MINECART), new ItemStack(Items.FURNACE_MINECART), new ItemStack(Items.HOPPER_MINECART),
						new ItemStack(Items.TNT_MINECART), new ItemStack(Items.COMMAND_BLOCK_MINECART), new ItemStack(Items.OAK_BOAT),
						new ItemStack(Items.SPRUCE_BOAT), new ItemStack(Items.BIRCH_BOAT), new ItemStack(Items.JUNGLE_BOAT),
						new ItemStack(Items.ACACIA_BOAT), new ItemStack(Items.DARK_OAK_BOAT), new ItemStack(Items.REPEATER),
						new ItemStack(Items.COMPARATOR), new ItemStack(Items.APPLE), new ItemStack(Items.GOLDEN_APPLE),
						new ItemStack(Items.ENCHANTED_GOLDEN_APPLE), new ItemStack(Items.STICK), new ItemStack(Items.DEBUG_STICK),
						new ItemStack(Items.BOWL), new ItemStack(Items.MUSHROOM_STEW), new ItemStack(Items.SUSPICIOUS_STEW),
						new ItemStack(Items.STRING), new ItemStack(Items.FEATHER), new ItemStack(Items.GUNPOWDER), new ItemStack(Items.WHEAT_SEEDS),
						new ItemStack(Items.WHEAT), new ItemStack(Items.CARROT), new ItemStack(Items.POTATO), new ItemStack(Items.BAKED_POTATO),
						new ItemStack(Items.POISONOUS_POTATO), new ItemStack(Items.PUMPKIN_PIE), new ItemStack(Items.GOLDEN_CARROT),
						new ItemStack(Items.BREAD), new ItemStack(Items.PUMPKIN_SEEDS), new ItemStack(Items.FLINT), new ItemStack(Items.LEATHER),
						new ItemStack(Items.SADDLE), new ItemStack(Items.BRICK), new ItemStack(Items.NETHER_BRICK), new ItemStack(Items.CLAY_BALL),
						new ItemStack(Items.SUGAR_CANE), new ItemStack(Items.PAPER), new ItemStack(Items.DRIED_KELP), new ItemStack(Items.SLIME_BALL),
						new ItemStack(Items.EGG), new ItemStack(Items.GLOWSTONE_DUST), new ItemStack(Items.BONE), new ItemStack(Items.SUGAR),
						new ItemStack(Items.CAKE), new ItemStack(Blocks.CANDLE_CAKE), new ItemStack(Blocks.WHITE_CANDLE_CAKE),
						new ItemStack(Blocks.ORANGE_CANDLE_CAKE), new ItemStack(Blocks.MAGENTA_CANDLE_CAKE),
						new ItemStack(Blocks.LIGHT_BLUE_CANDLE_CAKE), new ItemStack(Blocks.YELLOW_CANDLE_CAKE),
						new ItemStack(Blocks.LIME_CANDLE_CAKE), new ItemStack(Blocks.PINK_CANDLE_CAKE), new ItemStack(Blocks.GRAY_CANDLE_CAKE),
						new ItemStack(Blocks.LIGHT_GRAY_CANDLE_CAKE), new ItemStack(Blocks.CYAN_CANDLE_CAKE),
						new ItemStack(Blocks.PURPLE_CANDLE_CAKE), new ItemStack(Blocks.BLUE_CANDLE_CAKE), new ItemStack(Blocks.BROWN_CANDLE_CAKE),
						new ItemStack(Blocks.GREEN_CANDLE_CAKE), new ItemStack(Blocks.RED_CANDLE_CAKE), new ItemStack(Blocks.BLACK_CANDLE_CAKE),
						new ItemStack(Items.WHITE_BED), new ItemStack(Items.COOKIE), new ItemStack(Items.MELON_SLICE),
						new ItemStack(Items.MELON_SEEDS), new ItemStack(Items.SWEET_BERRIES), new ItemStack(Items.GLOW_BERRIES),
						new ItemStack(Items.COD), new ItemStack(Items.SALMON), new ItemStack(Items.TROPICAL_FISH), new ItemStack(Items.PUFFERFISH),
						new ItemStack(Items.COOKED_COD), new ItemStack(Items.COOKED_SALMON), new ItemStack(Items.PORKCHOP),
						new ItemStack(Items.COOKED_PORKCHOP), new ItemStack(Items.BEEF), new ItemStack(Items.COOKED_BEEF),
						new ItemStack(Items.CHICKEN), new ItemStack(Items.COOKED_CHICKEN), new ItemStack(Items.RABBIT),
						new ItemStack(Items.COOKED_RABBIT), new ItemStack(Items.RABBIT_FOOT), new ItemStack(Items.RABBIT_HIDE),
						new ItemStack(Items.RABBIT_STEW), new ItemStack(Items.MUTTON), new ItemStack(Items.COOKED_MUTTON),
						new ItemStack(Items.ROTTEN_FLESH), new ItemStack(Items.ENDER_PEARL), new ItemStack(Items.ENDER_EYE),
						new ItemStack(Items.END_CRYSTAL), new ItemStack(Items.SHULKER_SHELL), new ItemStack(Items.CHORUS_FRUIT),
						new ItemStack(Items.POPPED_CHORUS_FRUIT), new ItemStack(Items.BEETROOT), new ItemStack(Items.BEETROOT_SEEDS),
						new ItemStack(Items.BEETROOT_SOUP), new ItemStack(Items.GHAST_TEAR), new ItemStack(Items.NETHER_WART),
						new ItemStack(Items.GLASS_BOTTLE), new ItemStack(Items.POTION), new ItemStack(Items.SPLASH_POTION),
						new ItemStack(Items.LINGERING_POTION), new ItemStack(Items.DRAGON_BREATH), new ItemStack(Items.SPIDER_EYE),
						new ItemStack(Items.FERMENTED_SPIDER_EYE), new ItemStack(Items.BLAZE_ROD), new ItemStack(Items.BLAZE_POWDER),
						new ItemStack(Items.MAGMA_CREAM), new ItemStack(Items.BREWING_STAND), new ItemStack(Items.CAULDRON),
						new ItemStack(Items.GLISTERING_MELON_SLICE), new ItemStack(Items.CREEPER_SPAWN_EGG), new ItemStack(Items.SKELETON_SPAWN_EGG),
						new ItemStack(Items.SPIDER_SPAWN_EGG), new ItemStack(Items.ZOMBIE_SPAWN_EGG), new ItemStack(Items.SLIME_SPAWN_EGG),
						new ItemStack(Items.GHAST_SPAWN_EGG), new ItemStack(Items.ZOMBIFIED_PIGLIN_SPAWN_EGG),
						new ItemStack(Items.ENDERMAN_SPAWN_EGG), new ItemStack(Items.CAVE_SPIDER_SPAWN_EGG),
						new ItemStack(Items.SILVERFISH_SPAWN_EGG), new ItemStack(Items.BLAZE_SPAWN_EGG), new ItemStack(Items.MAGMA_CUBE_SPAWN_EGG),
						new ItemStack(Items.BAT_SPAWN_EGG), new ItemStack(Items.WITCH_SPAWN_EGG), new ItemStack(Items.ENDERMITE_SPAWN_EGG),
						new ItemStack(Items.GUARDIAN_SPAWN_EGG), new ItemStack(Items.PIG_SPAWN_EGG), new ItemStack(Items.SHEEP_SPAWN_EGG),
						new ItemStack(Items.COW_SPAWN_EGG), new ItemStack(Items.CHICKEN_SPAWN_EGG), new ItemStack(Items.SQUID_SPAWN_EGG),
						new ItemStack(Items.WOLF_SPAWN_EGG), new ItemStack(Items.MOOSHROOM_SPAWN_EGG), new ItemStack(Items.OCELOT_SPAWN_EGG),
						new ItemStack(Items.HORSE_SPAWN_EGG), new ItemStack(Items.RABBIT_SPAWN_EGG), new ItemStack(Items.VILLAGER_SPAWN_EGG),
						new ItemStack(Items.BEE_SPAWN_EGG), new ItemStack(Items.CAT_SPAWN_EGG), new ItemStack(Items.COD_SPAWN_EGG),
						new ItemStack(Items.DOLPHIN_SPAWN_EGG), new ItemStack(Items.DONKEY_SPAWN_EGG), new ItemStack(Items.DROWNED_SPAWN_EGG),
						new ItemStack(Items.ELDER_GUARDIAN_SPAWN_EGG), new ItemStack(Items.EVOKER_SPAWN_EGG), new ItemStack(Items.FOX_SPAWN_EGG),
						new ItemStack(Items.HUSK_SPAWN_EGG), new ItemStack(Items.LLAMA_SPAWN_EGG), new ItemStack(Items.MULE_SPAWN_EGG),
						new ItemStack(Items.PANDA_SPAWN_EGG), new ItemStack(Items.PARROT_SPAWN_EGG), new ItemStack(Items.PHANTOM_SPAWN_EGG),
						new ItemStack(Items.PILLAGER_SPAWN_EGG), new ItemStack(Items.POLAR_BEAR_SPAWN_EGG), new ItemStack(Items.PUFFERFISH_SPAWN_EGG),
						new ItemStack(Items.RAVAGER_SPAWN_EGG), new ItemStack(Items.SALMON_SPAWN_EGG), new ItemStack(Items.SHULKER_SPAWN_EGG),
						new ItemStack(Items.SKELETON_HORSE_SPAWN_EGG), new ItemStack(Items.STRAY_SPAWN_EGG),
						new ItemStack(Items.TRADER_LLAMA_SPAWN_EGG), new ItemStack(Items.TROPICAL_FISH_SPAWN_EGG),
						new ItemStack(Items.TURTLE_SPAWN_EGG), new ItemStack(Items.VEX_SPAWN_EGG), new ItemStack(Items.VINDICATOR_SPAWN_EGG),
						new ItemStack(Items.WANDERING_TRADER_SPAWN_EGG), new ItemStack(Items.WITHER_SKELETON_SPAWN_EGG),
						new ItemStack(Items.ZOMBIE_HORSE_SPAWN_EGG), new ItemStack(Items.ZOMBIE_VILLAGER_SPAWN_EGG),
						new ItemStack(Items.HOGLIN_SPAWN_EGG), new ItemStack(Items.PIGLIN_SPAWN_EGG), new ItemStack(Items.PIGLIN_BRUTE_SPAWN_EGG),
						new ItemStack(Items.STRIDER_SPAWN_EGG), new ItemStack(Items.ZOGLIN_SPAWN_EGG), new ItemStack(Items.AXOLOTL_SPAWN_EGG),
						new ItemStack(Items.GOAT_SPAWN_EGG), new ItemStack(Items.GLOW_SQUID_SPAWN_EGG), new ItemStack(Items.EXPERIENCE_BOTTLE),
						new ItemStack(Items.FIRE_CHARGE), new ItemStack(Items.SNOWBALL), new ItemStack(Items.BOOK),
						new ItemStack(Items.WRITABLE_BOOK), new ItemStack(Items.WRITTEN_BOOK), new ItemStack(Items.ENCHANTED_BOOK),
						new ItemStack(Items.KNOWLEDGE_BOOK), new ItemStack(Items.MUSIC_DISC_13), new ItemStack(Items.MUSIC_DISC_CAT),
						new ItemStack(Items.MUSIC_DISC_BLOCKS), new ItemStack(Items.MUSIC_DISC_CHIRP), new ItemStack(Items.MUSIC_DISC_FAR),
						new ItemStack(Items.MUSIC_DISC_MALL), new ItemStack(Items.MUSIC_DISC_MELLOHI), new ItemStack(Items.MUSIC_DISC_STAL),
						new ItemStack(Items.MUSIC_DISC_STRAD), new ItemStack(Items.MUSIC_DISC_WARD), new ItemStack(Items.MUSIC_DISC_11),
						new ItemStack(Items.MUSIC_DISC_WAIT), new ItemStack(Items.MUSIC_DISC_OTHERSIDE), new ItemStack(Items.MUSIC_DISC_PIGSTEP),
						new ItemStack(Items.SKELETON_SKULL), new ItemStack(Items.WITHER_SKELETON_SKULL), new ItemStack(Items.PLAYER_HEAD),
						new ItemStack(Items.ZOMBIE_HEAD), new ItemStack(Items.CREEPER_HEAD), new ItemStack(Items.DRAGON_HEAD),
						new ItemStack(Items.FIREWORK_STAR), new ItemStack(Items.FIREWORK_ROCKET), new ItemStack(Items.HONEYCOMB),
						new ItemStack(Items.HONEY_BOTTLE));
			}
		}, 1, -3f, new Item.Properties().tab(CreativeModeTab.TAB_TOOLS).fireResistant());
	}

	@Override
	public boolean hasContainerItem(ItemStack stack) {
		return true;
	}

	@Override
	public ItemStack getContainerItem(ItemStack itemstack) {
		ItemStack retval = new ItemStack(this);
		retval.setDamageValue(itemstack.getDamageValue() + 1);
		if (retval.getDamageValue() >= retval.getMaxDamage()) {
			return ItemStack.EMPTY;
		}
		return retval;
	}

	@Override
	public boolean isRepairable(ItemStack itemstack) {
		return false;
	}

	@Override
	public void appendHoverText(ItemStack itemstack, Level world, List<Component> list, TooltipFlag flag) {
		super.appendHoverText(itemstack, world, list, flag);
		list.add(new TextComponent("kill evrerything and destroy everyone! good luck!"));
	}
}
